#!/bin/bash

if [ -z $1 ]
then
	echo "Missing theme argument"
	exit
fi

theme=$1
themedir=$MY_THEMES_DIR/$theme
configdir=$MY_CONFIG_DIR

echo "Setting up $theme theme"
# move theme files
cp $themedir/colorlist $configdir/Xconfigfiles/colorlist
cp $themedir/termitetheme $configdir/termite/termitetheme
cp $themedir/dunstcolors $configdir/dunst/dunstcolors
cp $themedir/theme.vim $MY_VIM_HOME/theme.vim
cp $themedir/fehbg $configdir/other-scripts/fehbg

rm $configdir/alacritty/colors.yml.bak
mv $configdir/alacritty/colors.yml $configdir/alacritty/colors.yml.bak
rm $configdir/newsboat/colors.bak
mv $configdir/newsboat/colors $configdir/newsboat/colors.bak
ln -sT $themedir/alacritty_colors.yml $configdir/alacritty/colors.yml
ln -sT $themedir/sway_colors $configdir/sway/conf.d/99_colors_override
ln -sT $themedir/newsboatcolors $configdir/newsboat/colors

FG=black
if [[ $theme == *"light"* ]]; then
	FG=white
fi

echo "PRIMARY_FG=$FG" > ~/.dotfiles/symlinks/zshrc.theme
echo "$theme detected as a $FG theme"
notify-send "$theme detected as $FG theme" --icon=dialog-information
