#!/bin/sh

xset r rate 200 25 &
xbindkeys -p &
xinput set-prop 14 284 1 &
~/bin/settings/reload-configurations &
compton --config ~/.config/compton.conf -b &
dunst &
nm-applet &
python2 /usr/bin/mopidy &
