name: CI
on:
  push:
    branches: [ master ]

  workflow_dispatch:


jobs:
  bootstrap:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
      - name: Run bootstrap
        run: make bootstrap
        env:
          DOTFILES_CI: 1
  create-key:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
      - name: Run key creation
        run: echo "test\n\n" | make create_personal_ssh_github_key
        env:
          DOTFILES_CI: 1
