name: Neovim Nightly compatibility test
on:
  schedule:
    - cron: '0 12 * * *'

  workflow_dispatch:


jobs:
  bootstrap-and-check-nightly:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
      - name: Run bootstrap
        run: make bootstrap
        env:
          DOTFILES_CI: 1
      - name: Install neovim
        uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: nightly
      - name: Run neovim checks
        run: make check_neovim
        env:
          DOTFILES_CI: 1
