name: Neovim Nightly compatibility test
on:
  schedule:
    - cron: '0 12 * * *'

  workflow_dispatch:


jobs:
  bootstrap-and-check-nightly:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
      - name: Run bootstrap
        run: make bootstrap
        env:
          DOTFILES_CI: 1
      - name: Install neovim
        uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: nightly
      - name: Install packer
        if: ${{ matrix.platform != 'windows-latest' }}
        run: |
          git clone https://github.com/wbthomason/packer.nvim ~/.local/share/nvim/site/pack/packer/start/packer.nvim
      - name: Install packer on Windows
        if: ${{ matrix.platform == 'windows-latest' }}
        run: |
          git clone https://github.com/wbthomason/packer.nvim "$env:LOCALAPPDATA\nvim-data\site\pack\packer\start\packer.nvim"
      - name: Run neovim checks
        run: make check_neovim
        env:
          DOTFILES_CI: 1
